language: ruby

rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head
  - jruby-head
#  - rbx-2

cache: bundler

addons:
  apt:
    packages:
    - libgmp3-dev

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

install:
  - gem install rainbow -v 2.2.1
  - bundle install

script: bundle exec ruby performance/profile.rb

notifications:
  disable: true
